# This is a basic workflow to help you get started with Actions

name: Build documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: florianl21/cosmos-docs:0.0.2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout master branches for all submodules
        env:
          SCRIPT_URL: ${{secrets.COSMOS_CHECKOUT_SCRIPT_URL}}
        run: |
          mkdir /tools
          cd /tools
          wget $SCRIPT_URL
          cd $GITHUB_WORKSPACE
          python3 /tools/try_submodule_checkout.py $GITHUB_WORKSPACE https://github.com/CosmOS-Creators/reference_project_stmIDE.git master
      - uses: actions/checkout@v2
        with:
          repository: CosmOS-Creators/CosmOS-Creators.github.io
          path: gh-pages
      - name: install pip requirements
        run: |
          pip3 install -r $GITHUB_WORKSPACE/Cosmos/docs/requirements.txt
      - name: generate documentation
        run: |
          cd $GITHUB_WORKSPACE/Cosmos/docs
          make html

#       - name: Commit documentation changes
#         run: |
#           git clone https://github.com/CosmOS-Creators/CosmOS-Creators.github.io.git --branch master single-branch gh-pages
#           cp -r docs/_build/html/* gh-pages/
#           cd gh-pages
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git add .
#           git commit -m "Update documentation" -a || true
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           branch: gh-pages
#           directory: gh-pages
#           github_token: ${{ secrets.GITHUB_TOKEN }}
